/* ================================================================ */
/*  ATTACHMENT SLOTS — 9 loại học liệu chuẩn Bộ GD&ĐT                */
/*  Nguồn: Cautruc chuong trinh Geleximco.xlsx — sheet "Học liệu"   */
/* ================================================================ */

export type AttachmentSlotType =
  | "organization_plan"      // 1. Kế hoạch tổ chức (phân phối chương trình)
  | "teacher_training_doc"   // 2. Tài liệu bồi dưỡng giáo viên
  | "lesson_plan"            // 3. Kế hoạch bài dạy
  | "pptx"                   // 4. Bài giảng PPTX
  | "teacher_video"          // 5. Video hướng dẫn giáo viên
  | "student_video"          // 6. Video hướng dẫn học sinh
  | "student_worksheet"      // 7. Phiếu học tập của học sinh
  | "equipment_list"         // 8. Danh mục học liệu (auto-gen)
  | "exercises_assessment";  // 9. Bài tập, kiểm tra, đánh giá, mở rộng

export type AttachmentUser = "CBQL" | "GV" | "HS";

export interface AttachmentSlotTemplate {
  type: AttachmentSlotType;
  order: number;
  label: string;
  shortLabel: string;
  description: string;
  forUsers: AttachmentUser[];
  required: boolean;
  autoGenerated: boolean;
  acceptedTypes: string[];   // VD ['.docx', '.pdf', 'video']
  icon: string;              // lucide-react icon name
  color: string;
}

export const ATTACHMENT_SLOT_TEMPLATES: AttachmentSlotTemplate[] = [
  {
    type: "organization_plan",
    order: 1,
    label: "Kế hoạch tổ chức (phân phối chương trình theo tháng/tuần)",
    shortLabel: "Kế hoạch tổ chức",
    description: "Phân phối chương trình theo tháng/tuần. Dùng cho CBQL + GV lập kế hoạch tổ chức năm học.",
    forUsers: ["CBQL", "GV"],
    required: false,
    autoGenerated: false,
    acceptedTypes: [".docx", ".pdf", ".xlsx"],
    icon: "Calendar",
    color: "#0891b2",
  },
  {
    type: "teacher_training_doc",
    order: 2,
    label: "Tài liệu bồi dưỡng giáo viên",
    shortLabel: "Tài liệu BD GV",
    description: "Tài liệu giúp GV nắm vững phương pháp dạy + nội dung chuyên môn của bài.",
    forUsers: ["CBQL", "GV"],
    required: false,
    autoGenerated: false,
    acceptedTypes: [".pdf", ".docx", "video"],
    icon: "BookOpen",
    color: "#7c3aed",
  },
  {
    type: "lesson_plan",
    order: 3,
    label: "Kế hoạch bài dạy theo bài học/chủ đề",
    shortLabel: "Kế hoạch bài dạy",
    description: "Giáo án chi tiết — chuẩn Công văn 5512/BGDĐT.",
    forUsers: ["GV"],
    required: true,
    autoGenerated: false,
    acceptedTypes: [".docx", ".pdf"],
    icon: "FileText",
    color: "#990803",
  },
  {
    type: "pptx",
    order: 4,
    label: "Bài giảng PPTX theo bài học/chủ đề",
    shortLabel: "Bài giảng PPTX",
    description: "Slide trình chiếu cho GV dạy trên lớp.",
    forUsers: ["GV"],
    required: true,
    autoGenerated: false,
    acceptedTypes: [".pptx", ".pdf"],
    icon: "Presentation",
    color: "#dc2626",
  },
  {
    type: "teacher_video",
    order: 5,
    label: "Video hướng dẫn giáo viên",
    shortLabel: "Video GV",
    description: "Video GV xem trước để chuẩn bị bài hoặc tham khảo phương pháp.",
    forUsers: ["GV"],
    required: false,
    autoGenerated: false,
    acceptedTypes: [".mp4", "youtube"],
    icon: "Video",
    color: "#c8a84e",
  },
  {
    type: "student_video",
    order: 6,
    label: "Video hướng dẫn học sinh",
    shortLabel: "Video HS",
    description: "Video cho HS tự học tại nhà hoặc xem trong lớp.",
    forUsers: ["HS"],
    required: false,
    autoGenerated: false,
    acceptedTypes: [".mp4", "youtube"],
    icon: "PlayCircle",
    color: "#16a34a",
  },
  {
    type: "student_worksheet",
    order: 7,
    label: "Phiếu học tập của học sinh",
    shortLabel: "Phiếu học tập",
    description: "Worksheet HS điền trong tiết hoặc giao về nhà.",
    forUsers: ["HS"],
    required: true,
    autoGenerated: false,
    acceptedTypes: [".pdf", ".docx"],
    icon: "ClipboardList",
    color: "#0891b2",
  },
  {
    type: "equipment_list",
    order: 8,
    label: "Danh mục học liệu (thiết bị theo chủ đề/bài học)",
    shortLabel: "Danh mục thiết bị",
    description: "BOM thiết bị cần — auto-gen từ section 'Thiết bị cần' của bài.",
    forUsers: ["GV", "HS"],
    required: false,
    autoGenerated: true,
    acceptedTypes: ["auto"],
    icon: "Boxes",
    color: "#64748b",
  },
  {
    type: "exercises_assessment",
    order: 9,
    label: "Bài tập, kiểm tra, đánh giá, mở rộng",
    shortLabel: "Bài tập / Đánh giá",
    description: "Bộ bài tập về nhà + đề kiểm tra + bài mở rộng cho HS giỏi.",
    forUsers: ["GV", "HS"],
    required: true,
    autoGenerated: false,
    acceptedTypes: [".pdf", ".docx"],
    icon: "GraduationCap",
    color: "#7c3aed",
  },
];

export const REQUIRED_ATTACHMENT_SLOTS: AttachmentSlotType[] =
  ATTACHMENT_SLOT_TEMPLATES.filter((s) => s.required).map((s) => s.type);

export function getAttachmentSlotTemplate(type: AttachmentSlotType): AttachmentSlotTemplate | undefined {
  return ATTACHMENT_SLOT_TEMPLATES.find((s) => s.type === type);
}
