// ============================================
// LEARNING PATHS MODULE - Mock Data
// Reflects Geleximco corporate structure
// ============================================

import type {
  LearningPathFull,
  PathEnrollment,
  PathAssignment,
  PathTemplate,
  PathAnalytics,
} from "./types";
import { courseImages } from "../mock-data";

export const pathThumbnails = courseImages;

export const mockPathsFull: LearningPathFull[] = [
  {
    id: "LP001",
    title: "Lộ trình Quản lý Cấp trung",
    description: "Phát triển toàn diện năng lực lãnh đạo và quản trị cho các Team Lead, Trưởng phòng mới được bổ nhiệm tại Tập đoàn Geleximco.",
    thumbnail: courseImages[1],
    category: "Kỹ năng Lãnh đạo & Quản trị",
    level: "Nâng cao",
    status: "active",
    mandatory: true,
    department: "Ban Giám đốc Tập đoàn",
    subsidiary: "Tập đoàn Geleximco",
    targetPositions: ["Team Lead", "Trưởng phòng", "Phó phòng"],
    milestones: [
      { id: "M1", title: "Nền tảng Lãnh đạo", description: "Hiểu về vai trò và trách nhiệm quản lý", courseIds: ["C006"], order: 1, requiredCompletionRate: 80 },
      { id: "M2", title: "Kỹ năng Quản trị", description: "Quản lý đội nhóm và ra quyết định", courseIds: ["C001", "C008"], order: 2, requiredCompletionRate: 80 },
      { id: "M3", title: "Chiến lược & Dự án", description: "Quản lý dự án và tư duy chiến lược", courseIds: ["C005"], order: 3, requiredCompletionRate: 85 },
    ],
    courseIds: ["C006", "C001", "C008", "C005"],
    totalDuration: "72 giờ",
    totalCourses: 4,
    enrolledCount: 189,
    completionRate: 45,
    avgRating: 4.7,
    createdBy: "Nguyễn Văn Minh",
    createdAt: "2025-06-15",
    updatedAt: "2026-01-20",
    deadline: "2026-06-30",
    tags: ["Leadership", "Management", "Core"],
    prerequisites: [],
    certificateOnCompletion: true,
    estimatedWeeks: 12,
  },
  {
    id: "LP002",
    title: "Lộ trình Nhân sự mới (Onboarding)",
    description: "Chương trình hội nhập bắt buộc cho tất cả nhân viên mới gia nhập Tập đoàn Geleximco và các công ty thành viên.",
    thumbnail: courseImages[0],
    category: "Onboarding & Văn hóa Tập đoàn",
    level: "Cơ bản",
    status: "active",
    mandatory: true,
    department: "Ban Nhân sự Tập đoàn",
    subsidiary: "Tập đoàn Geleximco",
    targetPositions: ["Nhân viên mới", "Thực tập sinh"],
    milestones: [
      { id: "M1", title: "Chào mừng & Giới thiệu", description: "Tìm hiểu về Tập đoàn và văn hóa doanh nghiệp", courseIds: ["C006"], order: 1, requiredCompletionRate: 100 },
      { id: "M2", title: "Tuân thủ & Pháp luật", description: "Các quy định pháp luật và nội quy cần biết", courseIds: ["C007"], order: 2, requiredCompletionRate: 90 },
      { id: "M3", title: "Kỹ năng làm việc", description: "Kỹ năng giao tiếp và làm việc nhóm", courseIds: ["C008"], order: 3, requiredCompletionRate: 80 },
    ],
    courseIds: ["C006", "C007", "C008"],
    totalDuration: "30 giờ",
    totalCourses: 3,
    enrolledCount: 1340,
    completionRate: 88,
    avgRating: 4.4,
    createdBy: "Trần Thị Hương",
    createdAt: "2025-01-01",
    updatedAt: "2026-02-10",
    tags: ["Onboarding", "Mandatory", "Culture"],
    prerequisites: [],
    certificateOnCompletion: true,
    estimatedWeeks: 4,
  },
  {
    id: "LP003",
    title: "Lộ trình Chuyên viên Tài chính - Ngân hàng",
    description: "Nâng cao chuyên môn nghiệp vụ cho cán bộ khối Ngân hàng TMCP An Bình (ABBank) và Chứng khoán An Bình (ABS).",
    thumbnail: courseImages[6],
    category: "Nghiệp vụ Ngân hàng & Tín dụng",
    level: "Trung cấp",
    status: "active",
    mandatory: false,
    department: "Khối Ngân hàng Bán lẻ",
    subsidiary: "Ngân hàng TMCP An Bình (ABBank)",
    targetPositions: ["Chuyên viên Tín dụng", "Chuyên viên Tài chính", "Giao dịch viên"],
    milestones: [
      { id: "M1", title: "Nền tảng Tài chính", description: "Phân tích tài chính cơ bản", courseIds: ["C003"], order: 1, requiredCompletionRate: 80 },
      { id: "M2", title: "Tuân thủ Ngân hàng", description: "Quy định pháp luật ngành ngân hàng", courseIds: ["C007"], order: 2, requiredCompletionRate: 90 },
    ],
    courseIds: ["C003", "C007"],
    totalDuration: "32 giờ",
    totalCourses: 2,
    enrolledCount: 420,
    completionRate: 62,
    avgRating: 4.6,
    createdBy: "Lê Thị Thu Hà",
    createdAt: "2025-08-01",
    updatedAt: "2026-01-15",
    tags: ["Finance", "Banking", "ABBank"],
    prerequisites: ["LP002"],
    certificateOnCompletion: true,
    estimatedWeeks: 6,
  },
  {
    id: "LP004",
    title: "Lộ trình An toàn Mỏ & Khai khoáng",
    description: "Đào tạo bắt buộc về an toàn lao động cho toàn bộ nhân sự khối sản xuất tại Khoáng sản Geleximco và Xi măng Thăng Long.",
    thumbnail: courseImages[7],
    category: "An toàn Mỏ & Khai khoáng",
    level: "Cơ bản",
    status: "active",
    mandatory: true,
    department: "Ban An toàn Mỏ & Lao động",
    subsidiary: "Khoáng sản Geleximco",
    targetPositions: ["Kỹ sư Khai thác", "Công nhân Mỏ", "Kỹ thuật viên"],
    milestones: [
      { id: "M1", title: "An toàn Cơ bản", description: "Nguyên tắc an toàn lao động cơ bản", courseIds: ["C002"], order: 1, requiredCompletionRate: 100 },
      { id: "M2", title: "Tuân thủ Pháp luật", description: "Quy chuẩn quốc gia về an toàn mỏ", courseIds: ["C007"], order: 2, requiredCompletionRate: 95 },
    ],
    courseIds: ["C002", "C007"],
    totalDuration: "28 giờ",
    totalCourses: 2,
    enrolledCount: 860,
    completionRate: 91,
    avgRating: 4.5,
    createdBy: "Trần Minh Đức",
    createdAt: "2025-03-01",
    updatedAt: "2026-02-01",
    deadline: "2026-03-31",
    tags: ["Safety", "Mining", "Mandatory"],
    prerequisites: [],
    certificateOnCompletion: true,
    estimatedWeeks: 4,
  },
  {
    id: "LP005",
    title: "Lộ trình Marketing & Kinh doanh BĐS",
    description: "Phát triển năng lực marketing số và kỹ năng kinh doanh cho khối Bất động sản Geleximco.",
    thumbnail: courseImages[2],
    category: "Marketing & Truyền thông Thương hiệu",
    level: "Trung cấp",
    status: "active",
    mandatory: false,
    department: "Ban Marketing BĐS",
    subsidiary: "BĐS Geleximco - KĐT Lê Trọng Tấn",
    targetPositions: ["Chuyên viên Marketing", "Trưởng nhóm Kinh doanh", "Sale Executive"],
    milestones: [
      { id: "M1", title: "Digital Marketing", description: "Chiến lược marketing số toàn diện", courseIds: ["C004"], order: 1, requiredCompletionRate: 80 },
      { id: "M2", title: "Giao tiếp & Đàm phán", description: "Kỹ năng giao tiếp trong kinh doanh BĐS", courseIds: ["C008"], order: 2, requiredCompletionRate: 75 },
      { id: "M3", title: "Quản lý Dự án BĐS", description: "Quản lý dự án theo chuẩn PMI cho BĐS", courseIds: ["C005"], order: 3, requiredCompletionRate: 80 },
    ],
    courseIds: ["C004", "C008", "C005"],
    totalDuration: "58 giờ",
    totalCourses: 3,
    enrolledCount: 235,
    completionRate: 54,
    avgRating: 4.5,
    createdBy: "Phạm Anh Tuấn",
    createdAt: "2025-09-01",
    updatedAt: "2026-01-25",
    tags: ["Marketing", "RealEstate", "Sales"],
    prerequisites: ["LP002"],
    certificateOnCompletion: true,
    estimatedWeeks: 10,
  },
  {
    id: "LP006",
    title: "Lộ trình Chuyển đổi số & CNTT",
    description: "Nâng cao năng lực công nghệ thông tin cho toàn bộ nhân sự Tập đoàn trong chiến lược chuyển đổi số.",
    thumbnail: courseImages[4],
    category: "CNTT & Chuyển đổi số",
    level: "Trung cấp",
    status: "active",
    mandatory: false,
    department: "Ban CNTT & Chuyển đổi số",
    subsidiary: "Tập đoàn Geleximco",
    targetPositions: ["Toàn bộ nhân sự", "IT Staff", "Digital Champion"],
    milestones: [
      { id: "M1", title: "Nền tảng số", description: "Kiến thức cơ bản về chuyển đổi số", courseIds: ["C008"], order: 1, requiredCompletionRate: 80 },
      { id: "M2", title: "Ứng dụng Công nghệ", description: "Sử dụng công cụ số trong công việc", courseIds: ["C006"], order: 2, requiredCompletionRate: 80 },
    ],
    courseIds: ["C008", "C006"],
    totalDuration: "18 giờ",
    totalCourses: 2,
    enrolledCount: 1580,
    completionRate: 72,
    avgRating: 4.3,
    createdBy: "Đỗ Minh Châu",
    createdAt: "2025-10-01",
    updatedAt: "2026-02-05",
    tags: ["Digital", "IT", "Transformation"],
    prerequisites: [],
    certificateOnCompletion: false,
    estimatedWeeks: 3,
  },
  {
    id: "LP007",
    title: "Lộ trình Vận hành Nhà máy Điện",
    description: "Đào tạo chuyên sâu cho kỹ sư và nhân viên vận hành tại Nhiệt điện Thăng Long và các dự án năng lượng tái tạo.",
    thumbnail: courseImages[3],
    category: "Vận hành Nhà máy Điện",
    level: "Chuyên gia",
    status: "active",
    mandatory: true,
    department: "Ban Vận hành Nhà máy Điện",
    subsidiary: "Nhiệt điện Thăng Long",
    targetPositions: ["Kỹ sư Vận hành", "Trưởng ca", "Kỹ thuật viên Điện"],
    milestones: [
      { id: "M1", title: "An toàn Điện", description: "An toàn lao động trong vận hành điện", courseIds: ["C002"], order: 1, requiredCompletionRate: 100 },
      { id: "M2", title: "Tuân thủ & Quy trình", description: "Quy trình vận hành chuẩn", courseIds: ["C007"], order: 2, requiredCompletionRate: 95 },
    ],
    courseIds: ["C002", "C007"],
    totalDuration: "40 giờ",
    totalCourses: 2,
    enrolledCount: 145,
    completionRate: 78,
    avgRating: 4.8,
    createdBy: "KS. Nguyễn Quang Huy",
    createdAt: "2025-05-01",
    updatedAt: "2026-01-30",
    deadline: "2026-04-30",
    tags: ["Energy", "Power", "Operations"],
    prerequisites: [],
    certificateOnCompletion: true,
    estimatedWeeks: 8,
  },
  {
    id: "LP008",
    title: "Lộ trình ESG & Phát triển Bền vững",
    description: "Đào tạo về tiêu chuẩn ESG, phát triển bền vững và trách nhiệm xã hội doanh nghiệp cho cấp quản lý.",
    thumbnail: courseImages[5],
    category: "ESG & Phát triển Bền vững",
    level: "Nâng cao",
    status: "draft",
    mandatory: false,
    department: "Ban Chiến lược & Phát triển",
    subsidiary: "Tập đoàn Geleximco",
    targetPositions: ["Quản lý Cấp cao", "Giám đốc Đơn vị", "Chuyên viên CSR"],
    milestones: [
      { id: "M1", title: "Giới thiệu ESG", description: "Khái niệm và framework ESG", courseIds: ["C006"], order: 1, requiredCompletionRate: 80 },
    ],
    courseIds: ["C006"],
    totalDuration: "16 giờ",
    totalCourses: 1,
    enrolledCount: 0,
    completionRate: 0,
    avgRating: 0,
    createdBy: "Nguyễn Văn Minh",
    createdAt: "2026-02-01",
    updatedAt: "2026-03-01",
    tags: ["ESG", "Sustainability", "CSR"],
    prerequisites: ["LP001"],
    certificateOnCompletion: true,
    estimatedWeeks: 3,
  },
];

// Enrollment data for learner view
export const mockEnrollments: PathEnrollment[] = [
  {
    id: "PE001", pathId: "LP002", userId: "U003", userName: "Lê Hoàng Nam",
    userDepartment: "Khối Ngân hàng Bán lẻ", userSubsidiary: "ABBank",
    enrolledDate: "2025-12-01", deadline: "2026-03-31", progress: 85,
    completedCourses: 2, totalCourses: 3, currentCourseId: "C008",
    currentMilestoneId: "M3", status: "in_progress", lastAccessDate: "2026-03-10",
    totalHoursSpent: 22, certificateIssued: false,
  },
  {
    id: "PE002", pathId: "LP003", userId: "U003", userName: "Lê Hoàng Nam",
    userDepartment: "Khối Ngân hàng Bán lẻ", userSubsidiary: "ABBank",
    enrolledDate: "2026-01-15", progress: 40,
    completedCourses: 1, totalCourses: 2, currentCourseId: "C007",
    currentMilestoneId: "M2", status: "in_progress", lastAccessDate: "2026-03-09",
    totalHoursSpent: 14, certificateIssued: false,
  },
  {
    id: "PE003", pathId: "LP006", userId: "U003", userName: "Lê Hoàng Nam",
    userDepartment: "Khối Ngân hàng Bán lẻ", userSubsidiary: "ABBank",
    enrolledDate: "2026-02-01", progress: 100,
    completedCourses: 2, totalCourses: 2, currentCourseId: "",
    currentMilestoneId: "", status: "completed", lastAccessDate: "2026-03-05",
    totalHoursSpent: 18, certificateIssued: true,
  },
  // More enrollments from various users for admin stats
  {
    id: "PE004", pathId: "LP001", userId: "E002", userName: "Trần Thị Hương",
    userDepartment: "Nhân sự", userSubsidiary: "Tập đoàn Geleximco",
    enrolledDate: "2025-07-01", deadline: "2026-06-30", progress: 65,
    completedCourses: 2, totalCourses: 4, currentCourseId: "C008",
    currentMilestoneId: "M2", status: "in_progress", lastAccessDate: "2026-03-08",
    totalHoursSpent: 48, certificateIssued: false,
  },
  {
    id: "PE005", pathId: "LP004", userId: "E006", userName: "Vũ Đức Thắng",
    userDepartment: "Kỹ thuật", userSubsidiary: "Khoáng sản Geleximco",
    enrolledDate: "2025-10-01", deadline: "2026-03-31", progress: 95,
    completedCourses: 2, totalCourses: 2, currentCourseId: "",
    currentMilestoneId: "", status: "completed", lastAccessDate: "2026-03-01",
    totalHoursSpent: 26, certificateIssued: true,
  },
  {
    id: "PE006", pathId: "LP002", userId: "E008", userName: "Ngô Thị Mai",
    userDepartment: "Kinh doanh", userSubsidiary: "BĐS Lê Trọng Tấn",
    enrolledDate: "2025-11-15", progress: 100,
    completedCourses: 3, totalCourses: 3, currentCourseId: "",
    currentMilestoneId: "", status: "completed", lastAccessDate: "2026-02-20",
    totalHoursSpent: 30, certificateIssued: true,
  },
  {
    id: "PE007", pathId: "LP005", userId: "E008", userName: "Ngô Thị Mai",
    userDepartment: "Kinh doanh", userSubsidiary: "BĐS Lê Trọng Tấn",
    enrolledDate: "2026-01-10", progress: 25,
    completedCourses: 0, totalCourses: 3, currentCourseId: "C004",
    currentMilestoneId: "M1", status: "in_progress", lastAccessDate: "2026-03-09",
    totalHoursSpent: 8, certificateIssued: false,
  },
  {
    id: "PE008", pathId: "LP001", userId: "E007", userName: "Đỗ Minh Châu",
    userDepartment: "IT & Công nghệ", userSubsidiary: "Tập đoàn Geleximco",
    enrolledDate: "2025-08-01", deadline: "2026-06-30", progress: 50,
    completedCourses: 2, totalCourses: 4, currentCourseId: "C001",
    currentMilestoneId: "M2", status: "in_progress", lastAccessDate: "2026-03-07",
    totalHoursSpent: 36, certificateIssued: false,
  },
];

export const mockAssignments: PathAssignment[] = [
  {
    id: "PA001", pathId: "LP002", pathTitle: "Lộ trình Nhân sự mới (Onboarding)",
    assignedTo: { type: "subsidiary", name: "Tất cả Công ty thành viên", count: 14 },
    assignedBy: "Nguyễn Văn Minh", assignedDate: "2025-01-15", deadline: "2026-12-31",
    status: "active", enrolledCount: 1340, completedCount: 1180,
  },
  {
    id: "PA002", pathId: "LP004", pathTitle: "Lộ trình An toàn Mỏ & Khai khoáng",
    assignedTo: { type: "subsidiary", name: "Khoáng sản Geleximco", count: 1 },
    assignedBy: "Nguyễn Văn Minh", assignedDate: "2025-03-15", deadline: "2026-03-31",
    status: "active", enrolledCount: 860, completedCount: 780,
  },
  {
    id: "PA003", pathId: "LP001", pathTitle: "Lộ trình Quản lý Cấp trung",
    assignedTo: { type: "position", name: "Trưởng phòng / Team Lead", count: 189 },
    assignedBy: "Nguyễn Văn Minh", assignedDate: "2025-06-20", deadline: "2026-06-30",
    status: "active", enrolledCount: 189, completedCount: 85,
  },
  {
    id: "PA004", pathId: "LP003", pathTitle: "Lộ trình Chuyên viên Tài chính",
    assignedTo: { type: "subsidiary", name: "ABBank + ABS", count: 2 },
    assignedBy: "Trần Thị Hương", assignedDate: "2025-08-10", deadline: "2026-08-31",
    status: "active", enrolledCount: 420, completedCount: 260,
  },
  {
    id: "PA005", pathId: "LP005", pathTitle: "Lộ trình Marketing & Kinh doanh BĐS",
    assignedTo: { type: "department", name: "Ban Marketing BĐS + Ban Kinh doanh BĐS", count: 2 },
    assignedBy: "Phạm Anh Tuấn", assignedDate: "2025-09-15", deadline: "2026-09-30",
    status: "active", enrolledCount: 235, completedCount: 127,
  },
  {
    id: "PA006", pathId: "LP007", pathTitle: "Lộ trình Vận hành Nhà máy Điện",
    assignedTo: { type: "subsidiary", name: "Nhiệt điện Thăng Long", count: 1 },
    assignedBy: "Nguyễn Văn Minh", assignedDate: "2025-05-20", deadline: "2026-04-30",
    status: "active", enrolledCount: 145, completedCount: 113,
  },
];

export const mockTemplates: PathTemplate[] = [
  { id: "T001", title: "Onboarding Nhân viên mới", description: "Template chuẩn cho chương trình hội nhập nhân viên mới", category: "Onboarding", level: "Cơ bản", courseCount: 3, estimatedWeeks: 4, usageCount: 14, rating: 4.6, tags: ["Onboarding", "HR"], icon: "🎯" },
  { id: "T002", title: "Phát triển Quản lý", description: "Template phát triển năng lực lãnh đạo cho cấp quản lý", category: "Leadership", level: "Nâng cao", courseCount: 5, estimatedWeeks: 16, usageCount: 8, rating: 4.8, tags: ["Leadership", "Management"], icon: "👔" },
  { id: "T003", title: "An toàn Lao động", description: "Template đào tạo an toàn bắt buộc cho khối sản xuất", category: "Safety", level: "Cơ bản", courseCount: 3, estimatedWeeks: 4, usageCount: 6, rating: 4.5, tags: ["Safety", "Compliance"], icon: "🦺" },
  { id: "T004", title: "Chuyên môn Nghiệp vụ", description: "Template nâng cao chuyên môn theo ngành nghề cụ thể", category: "Professional", level: "Trung cấp", courseCount: 4, estimatedWeeks: 8, usageCount: 10, rating: 4.4, tags: ["Professional", "Skills"], icon: "📚" },
  { id: "T005", title: "Chuyển đổi số", description: "Template đào tạo kỹ năng số cho toàn tổ chức", category: "Digital", level: "Cơ bản", courseCount: 3, estimatedWeeks: 6, usageCount: 12, rating: 4.3, tags: ["Digital", "IT"], icon: "💻" },
  { id: "T006", title: "Tuân thủ & Pháp luật", description: "Template đào tạo tuân thủ pháp luật định kỳ", category: "Compliance", level: "Cơ bản", courseCount: 2, estimatedWeeks: 3, usageCount: 14, rating: 4.2, tags: ["Compliance", "Legal"], icon: "⚖️" },
];

export const mockPathAnalytics: PathAnalytics = {
  pathId: "all",
  monthlyEnrollments: [
    { month: "T1", count: 245 }, { month: "T2", count: 310 }, { month: "T3", count: 280 },
    { month: "T4", count: 420 }, { month: "T5", count: 380 }, { month: "T6", count: 510 },
    { month: "T7", count: 450 }, { month: "T8", count: 620 }, { month: "T9", count: 580 },
    { month: "T10", count: 490 }, { month: "T11", count: 710 }, { month: "T12", count: 830 },
  ],
  completionTrend: [
    { month: "T1", rate: 58 }, { month: "T2", rate: 62 }, { month: "T3", rate: 60 },
    { month: "T4", rate: 65 }, { month: "T5", rate: 68 }, { month: "T6", rate: 72 },
    { month: "T7", rate: 70 }, { month: "T8", rate: 75 }, { month: "T9", rate: 78 },
    { month: "T10", rate: 76 }, { month: "T11", rate: 82 }, { month: "T12", rate: 85 },
  ],
  departmentBreakdown: [
    { dept: "Ban GĐ TĐ", enrolled: 45, completed: 38 },
    { dept: "Nhân sự TĐ", enrolled: 120, completed: 105 },
    { dept: "ABBank", enrolled: 420, completed: 260 },
    { dept: "Khoáng sản", enrolled: 860, completed: 780 },
    { dept: "BĐS", enrolled: 350, completed: 210 },
    { dept: "Nhiệt điện", enrolled: 145, completed: 113 },
    { dept: "CNTT", enrolled: 65, completed: 58 },
    { dept: "Marketing", enrolled: 235, completed: 127 },
  ],
  avgCompletionDays: 42,
  dropOffPoints: [
    { courseTitle: "Quản lý Dự án theo PMI", dropRate: 28 },
    { courseTitle: "Phân tích Tài chính DN", dropRate: 22 },
    { courseTitle: "An toàn LĐ trong XD", dropRate: 8 },
    { courseTitle: "Marketing số", dropRate: 18 },
    { courseTitle: "Tuân thủ Pháp luật", dropRate: 12 },
  ],
};

// AI Recommendations for learner
export const aiRecommendations = [
  {
    pathId: "LP001",
    reason: "Dựa trên vị trí Chuyên viên Phân tích Tín dụng, lộ trình này sẽ giúp bạn phát triển kỹ năng quản lý để thăng tiến lên vị trí Trưởng nhóm.",
    matchScore: 87,
    skills: ["Lãnh đạo", "Quản lý đội nhóm", "Ra quyết định"],
  },
  {
    pathId: "LP005",
    reason: "Kỹ năng marketing số đang là xu hướng quan trọng trong ngành ngân hàng hiện đại. Lộ trình này bổ sung kiến thức cross-functional cho bạn.",
    matchScore: 72,
    skills: ["Digital Marketing", "Branding", "Customer Engagement"],
  },
  {
    pathId: "LP007",
    reason: "Tập đoàn đang mở rộng lĩnh vực năng lượng. Hiểu biết về vận hành nhà máy điện sẽ tăng cơ hội luân chuyển nội bộ.",
    matchScore: 45,
    skills: ["Năng lượng", "Vận hành", "An toàn"],
  },
];
