export { Home } from "./Home";
export { About } from "./About";
export { SolutionsHub } from "./SolutionsHub";
export { SolutionMinimum, SolutionBasic, SolutionAdvanced } from "./SolutionDetail";
export { ProgramsHub } from "./ProgramsHub";
export { ProgramCT1, ProgramCT2, ProgramCT3, ProgramCT4, ProgramCT5 } from "./ProgramDetail";
export { PartnersHub } from "./PartnersHub";
export { PartnerGeleximco, PartnerEBD, PartnerNexta } from "./PartnerDetail";
export { NewsList } from "./NewsList";
export { NewsDetail } from "./NewsDetail";
export { Events } from "./Events";
export { Contact } from "./Contact";
export { SupportHub } from "./SupportHub";
export { FAQ } from "./FAQ";
export { KBHub } from "./KBHub";
export { KBArticle } from "./KBArticle";
export { TicketNew } from "./TicketNew";
export { Downloads } from "./Downloads";
export { PublicComingSoon } from "./PublicComingSoon";
