import type { DownloadItem } from "./types";

export const downloads: DownloadItem[] = [
  {
    id: "dl1",
    title: "Brochure tổng quan Geleximco STEM Platform",
    description: "Tổng quan đầy đủ về hệ sinh thái, 3 gói phòng STEM, 5 chương trình và lộ trình triển khai.",
    category: "Tài liệu marketing",
    fileType: "PDF",
    fileSize: "3.2 MB",
    url: "#",
    updatedAt: "2026-04-01",
    targetAudience: "Hiệu trưởng, Ban Giám hiệu",
  },
  {
    id: "dl2",
    title: "So sánh 3 gói Phòng STEM (Tối thiểu / Cơ bản / Nâng cao)",
    description: "Bảng so sánh chi tiết tính năng, thiết bị, chương trình hỗ trợ và chi phí của 3 gói phòng STEM.",
    category: "Tài liệu marketing",
    fileType: "PDF",
    fileSize: "1.8 MB",
    url: "#",
    updatedAt: "2026-04-01",
    targetAudience: "Hiệu trưởng, Ban Tài chính",
  },
  {
    id: "dl3",
    title: "Bộ tài liệu mẫu CT1 — Tích hợp nội môn (Toán 6, Lý 9)",
    description: "Kế hoạch bài dạy mẫu, phiếu học tập, slide PPTX cho CT1 bậc THCS. Mapping chuẩn SGK Kết nối tri thức.",
    category: "Học liệu mẫu",
    fileType: "ZIP",
    fileSize: "24.6 MB",
    url: "#",
    updatedAt: "2026-03-15",
    targetAudience: "Giáo viên THCS",
  },
  {
    id: "dl4",
    title: "Hướng dẫn vận hành Phòng STEM Cơ bản",
    description: "Quy trình sử dụng, bảo quản thiết bị, quản lý học liệu và xếp TKB cho phòng STEM Cơ bản.",
    category: "Hướng dẫn vận hành",
    fileType: "PDF",
    fileSize: "5.1 MB",
    url: "#",
    updatedAt: "2026-03-01",
    targetAudience: "GV phụ trách phòng STEM, Ban Giám hiệu",
  },
  {
    id: "dl5",
    title: "Quy trình đặt hàng và triển khai Phòng STEM",
    description: "Quy trình 7 bước từ ký hợp đồng, lên danh sách BOM, lắp đặt, nghiệm thu đến bàn giao.",
    category: "Hướng dẫn vận hành",
    fileType: "PDF",
    fileSize: "2.3 MB",
    url: "#",
    updatedAt: "2026-02-15",
    targetAudience: "Phòng Kế hoạch-Tài chính trường",
  },
  {
    id: "dl6",
    title: "Checklist kiểm tra thiết bị phòng STEM hằng tháng",
    description: "Biểu mẫu kiểm tra định kỳ thiết bị, phần mềm và học liệu. Dùng cho GV phụ trách phòng STEM.",
    category: "Biểu mẫu",
    fileType: "XLSX",
    fileSize: "0.3 MB",
    url: "#",
    updatedAt: "2026-01-10",
    targetAudience: "GV phụ trách phòng STEM",
  },
  {
    id: "dl7",
    title: "Mẫu kế hoạch bài dạy STEM (CT2 — Liên môn Toán-Lý)",
    description: "Template kế hoạch bài dạy tích hợp liên môn, có kịch bản, rubric đánh giá và danh mục thiết bị.",
    category: "Biểu mẫu",
    fileType: "DOCX",
    fileSize: "0.8 MB",
    url: "#",
    updatedAt: "2026-01-05",
    targetAudience: "Giáo viên bộ môn",
  },
  {
    id: "dl8",
    title: "Báo cáo tác động STEM 2025 — Geleximco",
    description: "Kết quả khảo sát tác động của chương trình STEM tại 300+ trường trong năm học 2025-2026.",
    category: "Báo cáo & Nghiên cứu",
    fileType: "PDF",
    fileSize: "4.7 MB",
    url: "#",
    updatedAt: "2025-12-20",
    targetAudience: "Tất cả",
  },
];
