import type { KBArticle } from "./types";

export const kbArticles: KBArticle[] = [
  {
    id: "kb1",
    slug: "huong-dan-dang-nhap-lan-dau",
    category: "Bắt đầu",
    title: "Hướng dẫn đăng nhập lần đầu vào hệ thống",
    excerpt: "Các bước đăng nhập, đổi mật khẩu và cài đặt thông tin cá nhân sau khi nhận tài khoản.",
    body: "Sau khi nhận email kích hoạt từ quản trị viên trường, hãy làm theo các bước sau: (1) Mở link kích hoạt trong email. (2) Đặt mật khẩu mới (tối thiểu 8 ký tự, có chữ hoa, số và ký tự đặc biệt). (3) Điền thông tin cá nhân. (4) Chọn môn dạy/lớp phụ trách. (5) Đăng nhập và khám phá hệ thống.",
    lastUpdated: "2026-04-01",
    tags: ["đăng nhập", "tài khoản", "bắt đầu"],
  },
  {
    id: "kb2",
    slug: "tao-lich-stem-cho-lop",
    category: "Bắt đầu",
    title: "Tạo lịch STEM và phân công giáo viên",
    excerpt: "Hướng dẫn Ban Giám hiệu tạo lịch STEM, phân công GV phụ trách và thông báo cho HS.",
    body: "Quản lý trường có thể tạo lịch STEM từ menu Quản lý lịch học. Chọn lớp, chọn phòng STEM, chọn chương trình CT và phân công GV. Hệ thống tự đồng bộ với TKB K12Online/VnEdu nếu trường đã tích hợp.",
    lastUpdated: "2026-03-15",
    tags: ["lịch STEM", "TKB", "phân công GV"],
  },
  {
    id: "kb3",
    slug: "quan-ly-thiet-bi-phong-stem",
    category: "Vận hành",
    title: "Quản lý và kiểm kê thiết bị phòng STEM",
    excerpt: "Cách dùng module Kiểm kê thiết bị để theo dõi, báo hỏng và yêu cầu bảo hành.",
    body: "Module Kiểm kê thiết bị cho phép GV phụ trách quét mã QR thiết bị để xem thông tin bảo hành, lịch sử sửa chữa. Khi có thiết bị hỏng, tạo ticket bảo hành trực tiếp từ app. Hệ thống sẽ thông báo đến NCC trong 24 giờ.",
    lastUpdated: "2026-03-10",
    tags: ["thiết bị", "bảo hành", "kiểm kê"],
  },
  {
    id: "kb4",
    slug: "upload-tai-lieu-len-thu-vien",
    category: "Vận hành",
    title: "Upload tài liệu và học liệu lên thư viện trường",
    excerpt: "Hướng dẫn GV upload giáo án, bài giảng, phiếu học tập lên thư viện nội bộ của trường.",
    body: "Từ menu Tài nguyên → Thư viện nội bộ, GV có thể upload file (PDF, PPTX, DOCX, MP4). Gắn tag theo CT và lớp để dễ tìm kiếm. Tài liệu được chia sẻ trong nội bộ trường hoặc toàn hệ thống (nếu NCC cho phép).",
    lastUpdated: "2026-02-20",
    tags: ["tài liệu", "thư viện", "upload"],
  },
  {
    id: "kb5",
    slug: "theo-doi-tien-do-hoc-sinh",
    category: "Dạy học",
    title: "Theo dõi tiến độ học sinh qua hệ thống",
    excerpt: "Hướng dẫn GV xem báo cáo tiến độ, điểm số và tham gia bài kiểm tra của từng học sinh.",
    body: "Từ dashboard GV, chọn lớp và nhấn 'Tiến độ học sinh'. Hệ thống hiển thị % hoàn thành bài học, kết quả kiểm tra và thời gian học. Có thể export báo cáo PDF gửi cho phụ huynh hoặc Ban Giám hiệu.",
    lastUpdated: "2026-02-10",
    tags: ["tiến độ", "học sinh", "báo cáo"],
  },
  {
    id: "kb6",
    slug: "cau-hinh-tich-hop-vneduo-k12online",
    category: "Tích hợp hệ thống",
    title: "Cấu hình tích hợp VnEdu / K12Online",
    excerpt: "Hướng dẫn quản trị viên trường cấu hình đồng bộ tài khoản từ VnEdu hoặc K12Online.",
    body: "Vào Settings → Tích hợp hệ thống → chọn VnEdu hoặc K12Online. Nhập API Key và URL tenant từ hệ thống nguồn. Chạy test kết nối. Sau khi kết nối thành công, danh sách GV và HS sẽ đồng bộ tự động mỗi đêm lúc 2:00 SA.",
    lastUpdated: "2026-01-15",
    tags: ["VnEdu", "K12Online", "đồng bộ", "tích hợp"],
  },
  {
    id: "kb7",
    slug: "bao-cao-hieu-qua-stem",
    category: "Báo cáo",
    title: "Xuất báo cáo hiệu quả STEM gửi Phòng Giáo dục",
    excerpt: "Hướng dẫn Ban Giám hiệu tạo và xuất báo cáo hiệu quả STEM theo mẫu của Phòng/Sở GD&ĐT.",
    body: "Từ menu Báo cáo → chọn kỳ báo cáo → chọn mẫu (Phòng GD hoặc Sở GD). Hệ thống tổng hợp tự động từ dữ liệu TKB, tiến độ HS và kết quả kiểm tra. Xuất file Excel hoặc PDF theo chuẩn yêu cầu của cơ quan quản lý.",
    lastUpdated: "2026-01-05",
    tags: ["báo cáo", "Phòng GD", "Sở GD", "xuất file"],
  },
  {
    id: "kb8",
    slug: "reset-mat-khau-tai-khoan",
    category: "Tài khoản",
    title: "Đặt lại mật khẩu khi quên hoặc bị khóa tài khoản",
    excerpt: "Các bước tự đặt lại mật khẩu qua email hoặc liên hệ quản trị viên trường.",
    body: "Tại trang đăng nhập, nhấn 'Quên mật khẩu'. Nhập email đã đăng ký và nhấn gửi. Kiểm tra email (kể cả thư mục Spam) và nhấn link trong vòng 15 phút. Nếu không nhận được email, liên hệ quản trị viên trường hoặc hotline hỗ trợ Geleximco.",
    lastUpdated: "2025-12-10",
    tags: ["mật khẩu", "tài khoản", "đăng nhập"],
  },
];
