import type { ProgramInfo } from "./types";

export const stemPrograms: ProgramInfo[] = [
  {
    id: "CT1",
    name: "CT1",
    fullName: "Tích hợp nội môn",
    tagline: "GD STEM tích hợp trong môn học",
    description:
      "Dạy bài học của môn học theo phương thức STEM. Giáo viên các môn áp dụng tư duy STEM vào tiết học chính khóa.",
    dimension: "Môn học × Bậc học (Toán, Lý, Hóa, Sinh, Công nghệ...)",
    schedulingMode: "Chính khóa (đè lên giờ học chính)",
    teacherType: "Giáo viên bộ môn",
    suitableGrades: ["MN", "TH", "THCS", "THPT", "LC", "THPT_Nghe"],
    sgkMapping: true,
    sampleLessons: [
      "Toán 6: Đo lường với dụng cụ STEM",
      "Vật lý 9: Mạch điện đơn giản",
      "Hóa 10: Thí nghiệm phản ứng hóa học",
    ],
    materialTypes: [
      "Kế hoạch giáo dục",
      "Tài liệu bồi dưỡng GV",
      "Kế hoạch bài dạy",
      "Bài giảng PPTX",
      "Video hướng dẫn GV",
      "Video hướng dẫn HS",
      "Phiếu học tập",
      "Danh mục thiết bị",
      "Bài tập kiểm tra",
    ],
  },
  {
    id: "CT2",
    name: "CT2",
    fullName: "Tích hợp liên môn",
    tagline: "GD STEM tích hợp liên môn",
    description:
      "Dạy chủ đề tích hợp liên môn (môn chủ đạo + môn tích hợp). Giáo viên nhóm môn phối hợp dạy chủ đề chung.",
    dimension: "Nhóm môn × Bậc học (Toán-Lý, Lý-Hóa-Sinh, Toán-Công nghệ...)",
    schedulingMode: "Chính khóa (tiết chuyên đề)",
    teacherType: "Giáo viên nhóm môn (2-3 GV phối hợp)",
    suitableGrades: ["TH", "THCS", "THPT", "LC"],
    sgkMapping: true,
    sampleLessons: [
      "Toán-Lý 7: Thiết kế thuyền giấy mô hình",
      "Lý-Hóa 10: Năng lượng và phản ứng",
      "Sinh-Hóa 11: Vòng tuần hoàn các chất",
    ],
    materialTypes: ["Như CT1, tập trung vào kịch bản liên môn"],
  },
  {
    id: "CT3",
    name: "CT3",
    fullName: "Tăng cường đổi mới sáng tạo",
    tagline: "STEM tăng cường định hướng đổi mới, sáng tạo",
    description:
      "Coi như môn học dạy buổi 2. Vận dụng kiến thức các môn học để giải quyết vấn đề thực tế.",
    dimension: "Tăng cường 1-4 × Bậc học",
    schedulingMode: "Buổi 2 (sau giờ chính khóa)",
    teacherType: "Giáo viên nhà trường (đa môn)",
    suitableGrades: ["TH", "THCS", "THPT"],
    sgkMapping: false,
    sampleLessons: [
      "Thiết kế khẩu trang lọc khí",
      "Mô hình nhà thông minh",
      "Ứng dụng pin năng lượng mặt trời",
    ],
    materialTypes: ["Kịch bản project-based learning", "Rubric đánh giá", "Sản phẩm mẫu"],
  },
  {
    id: "CT4",
    name: "CT4",
    fullName: "Robotic / AI / IoT",
    tagline: "GD STEM Robotic, AI, IoT (tăng cường)",
    description:
      "Chương trình chuyên sâu về Robotics, Trí tuệ nhân tạo và Internet vạn vật cho học sinh đam mê công nghệ.",
    dimension: "4 chương trình con: Robotics 1, AI, IoT, Robotics+AI",
    schedulingMode: "Tăng cường (có thể xếp TKB hoặc CLB)",
    teacherType: "Giáo viên Tin học + GV có chuyên môn",
    suitableGrades: ["THCS", "THPT", "LC", "THPT_Nghe"],
    sgkMapping: false,
    sampleLessons: [
      "Lập trình robot mBot tự hành",
      "Nhận diện hình ảnh với AI",
      "Hệ thống tưới cây IoT tự động",
    ],
    materialTypes: [
      "Bộ kit Robotics",
      "SDK lập trình",
      "Bài học video",
      "Project mẫu",
      "Rubric đánh giá kỹ năng",
    ],
  },
  {
    id: "CT5",
    name: "CT5",
    fullName: "Trải nghiệm / NCKH",
    tagline: "Trải nghiệm thực tế / Nghiên cứu khoa học",
    description:
      "Dành cho CLB, học sinh có năng khiếu. Đưa HS tham gia nghiên cứu khoa học, thi NCKH-KT cấp tỉnh/quốc gia.",
    dimension: "Chủ đề 1-18 × Bậc học",
    schedulingMode: "CLB / Ngoại khóa (không xếp TKB cố định)",
    teacherType: "GV cố vấn năng khiếu / chuyên gia",
    suitableGrades: ["THCS", "THPT", "THPT_Nghe"],
    sgkMapping: false,
    sampleLessons: [
      "Dự án Bioplastic từ vỏ chuối",
      "Nghiên cứu ô nhiễm không khí khu vực",
      "Ứng dụng AI dự đoán dịch bệnh",
    ],
    materialTypes: [
      "Hướng dẫn phương pháp NCKH",
      "Template báo cáo khoa học",
      "Tài liệu tham khảo chuyên sâu",
      "Mentor support",
    ],
  },
];
